CapStone Mobile and Desktop version
mahdimahdawi/Capstone-project pull request #1
Opened 2022-07-28 14:30 UTC by mahdimahdawi

**This PR Contain**
- The name of the website cloud-code.
- For mobile version to accessing the pages hamburger menu us available.
- The Top Developer Section create dynamically using javaScript
-

2022-07-28 18:23 UTC, Whoistolu requested changes
Hi @mahdimahdawi 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️

- [ ]  _Check the inline comments under the review for sections to improve._

### Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

### N/A

Cheers and Happy coding!

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @whoistolu in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-28 18:23 UTC, Whoistolu commented on index.html
> +        </div>
- [ ] [REQUIRED] Kindly ensure that the `menu-item` class is spaced correctly and the margin right should be reduced so it will look closely like the template provided.
### Your design
![1](https://user-images.githubusercontent.com/58692590/181600059-8b050a55-ae84-47d4-a409-abce4df2650b.png)
### Provided template
![2](https://user-images.githubusercontent.com/58692590/181600158-d7c6c92c-37ed-418d-87f0-8ff4e7424ffc.png)

2022-07-28 18:23 UTC, Whoistolu commented on index.html
> +      </section>
- [ ] [REQUIRED] Kindly ensure that this section is well aligned to the left so that it gets aligned with the logo on the nav bar and the main-program card below am. By doing this, your design will look more like the template provided and you will have a better UI.

Your Implementation   |  Figma Design
:-------------------------:|:-------------------------:
![3](https://user-images.githubusercontent.com/58692590/181604023-07d70645-a4e1-447c-83b8-16c197a9854b.png) | ![4](https://user-images.githubusercontent.com/58692590/181604546-138803f4-1b9d-4d54-b5e5-fc7a83988c0d.png)

2022-07-28 18:23 UTC, Whoistolu commented on index.html
> +  <section class="about-page" id="about-page">
- [ ] [REQUIRED] The home page has the about page on it as well and we have the same on the about page as well. kindly note that the home page and the about page contents should be separated. Take a look at the [project template provided](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015) to see the contents of the homepage and the about page. Kindly ensure you fix this issue on the mobile version as well.

### Your design
![Screenshot from 2022-07-28 18-54-58](https://user-images.githubusercontent.com/58692590/181606636-13c031c5-370e-496e-9df5-14ec7afaa037.png)
- Take a look at this part of your design and see that the speaker section is just above the summit section, meanwhile the speaker is supposed to be on the homepage while the summit section is supposed to be on the about page. Kindly fix this.

2022-07-28 18:23 UTC, Whoistolu commented on README.md
> +[Live Demo Link](https://github.com/mahdimahdawi/Capstone-project)
- [ ] [REQUIRED] Kindly ensure that this project is deployed properly using Github pages and add the deployment link to your README in order to meet up with the project requirement. The link currently attached is the link to your project repository.

2022-07-28 18:23 UTC, Whoistolu commented on README.md
> +- This website is a Development website that you access to feameworks and top developers list.
- [ ] [REQUIRED] Please note that the project requirement states that you should make a video presentation with a maximum length of 5 minutes. The video should contain a clear description of your project, it should also contain a demo of the project, showing the pages in different screen sizes and you should highlight a piece of code you are most proud of.

- [ ] [REQUIRED] This README should contain an "Acknowledgements" section that gives appropriate credit to [Cindy Shin](https://www.behance.net/adagio07) the [author of the original design](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015), as required by the [Creative Commons License](https://creativecommons.org/licenses/).

2022-07-29 07:32 UTC, merged

2022-07-29 10:36 UTC, mahdimahdawi commented
**This PR contain **

Unfortunately i merged the pull request that pervious reviewer comment on that.
Changes that Reviewer Requested and Now Fixed

The Navbar for desktop version placed on the right place.
Freamworks placed on the right place.
Separated about page from home page.
The Live version link and the video link available on the README.md
The Acknowledgement is completed now.
Screenshot of pervious reviewer comment attached to this PR.
![Screenshot (101)](https://user-images.githubusercontent.com/59498020/181741811-e6f70ad5-e13c-426d-97d9-1b71a4d569a9.png)
![Screenshot (102)](https://user-images.githubusercontent.com/59498020/181741828-43f665cc-f82b-48e2-8e2f-cec954045dd9.png)
![Screenshot (103)](https://user-images.githubusercontent.com/59498020/181741843-fbb1d04c-7fc9-4e82-8855-009ce2186a3c.png)
![Screenshot (104)](https://user-images.githubusercontent.com/59498020/181741862-fd2456ef-92a8-4355-8d8f-6596dd241515.png)

2022-07-29 12:44 UTC, muneebulrehman reviewed
Hi @mahdimahdawi , 

Your project is complete!  There is nothing else to say other than... it's time to merge it 🥳
Congratulations! 🎉 

# Status: Approved✔️

## Highlights
- No linter errors
- Good design
- Good follow-up with the previous reviewer.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._